services:
  backend:
    build:
      context: ./Backend_Project_Manager_App
      dockerfile: Dockerfile.dev
    container_name: App_Backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/project_manag?schema=public"
    depends_on:
      - db
    volumes:
      - ./Backend_Project_Manager_App:/app:cached
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  db:
    image: postgres:15
    container_name: db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_manag
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend_Project_Manager_App
      dockerfile: Dockerfile.dev
    container_name: App_Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./Frontend_Project_Manager_App:/app:cached
    command: npm run dev

volumes:
  db_data:
